import mysql.connector

if __name__ == '__main__':
    mydb=mysql.connector.connect (
        host="localhost",
        user="root",
        password="root",
        database="biu_shoes",
        port='3307',
    )
    cursor=mydb.cursor ()
    # Summary that shows the total revenue generated by each shoe, across all orders.
    cursor.execute ("""
    CREATE OR REPLACE VIEW total_sales_per_shoe AS
        SELECT sh.shoe_name, sh.shoe_id, SUM(sh.price) AS total_revenue
        FROM shoe AS sh
            JOIN order_shoe AS os ON sh.shoe_id = os.shoe_id
        GROUP BY sh.shoe_id, sh.shoe_name;
    """)               
    # Display the entire view data.
    cursor.execute ("""
    SELECT *
    FROM total_sales_per_shoe;
    """)
    print (', '. join (str( row ) for row in cursor . fetchall ()
    ))
